import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const svg = readFileSync(process.argv[2], 'utf8');
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 1400 }, deviceScaleFactor: 2 });
await p.setContent(`<body style="margin:0;background:#fff">${svg}</body>`);
await p.waitForTimeout(400);
await p.locator('svg').first().screenshot({ path: process.argv[3] });
await b.close();
console.log('shot ->', process.argv[3]);
