import { chromium } from 'playwright';
const url = process.argv[2] || 'http://localhost:5399/artboard-demo.html';
const out = process.argv[3] || '.scratch/before.png';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1512, height: 900 } });
const errs = [];
p.on('console', m => m.type() === 'error' && errs.push(m.text()));
await p.goto(url, { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
await p.screenshot({ path: out });
console.log('shot', out, 'errors:', errs.length ? errs : 'none');
await b.close();
