import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const svg = readFileSync(process.argv[2], 'utf8');
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1000, height: 820 } });
await p.setContent(`<body style="margin:0">${svg}</body>`);
await p.waitForTimeout(400);
await p.screenshot({ path: process.argv[3] });
await b.close();
console.log('ok');
